#!/usr/bin/env python3
from os import sys,system
ps=[]
def pk():
    if len(sys.argv)==2:
        if sys.argv[1]=='s':
            print(len(ps))
            return
        k=0
        try:
            k=int(sys.argv[1])
        except:pass 
        print(k)
pk()
